*
241008
広告検索について

実施前と実施後の広告のCV栗

1_実施前

広告検索から何人の人が購入したか、どこをとおってかは今回はみない

2024-10-01 Tuesday

First,  I finish syoukai LP by October.
Second,  I create winter campaign LP by october.
Third: I start AI driven create.
* 2024-10-09 Wednesday

10月は指名停止でお願いします。 テスト結果はよかったのでぜひ継続したいのですが、現在急激に出荷が伸びており、商品の出荷が追いつかなくなっているためです。一旦11月に再開の方向でお願いいたします。
  モロヘイヤのキーワードの方もLPに変更しましたが、こちらのLPからもボトルを削除してパックだけにするのですが、審査が再度必要でしょうか。
* 2024-10-24 Thursday

what is coefficient?

what is alpha?
* 2024-10-28 Monday

                           <!--空ボトル入荷待ち-->
                            {% if product.id == 175 or product.id == 56 or product.id == 58 %} 
                               <!-- <div style="font-size:1rem; font-weight:bold; color:#BC6666;">入荷待ち</div>
                                <p style="font-size:0.8rem; color:#707070;">10月下旬ごろ入荷予定です</p> -->
* 2024-10-28 Monday

                             <!--空ボトル入荷待ち -->
                             {% if product.id == 175 or product.id == 56 or product.id == 58 %}
                             <div style="text-align:center; width:100%; margin-top:10px;">
                                <span style="font-size:1rem; font-weight:bold; color:#BC6666;">入荷待ち</span><br />
                                <span style="font-size:0.8rem; color:#707070;">10月下旬ごろ入荷予定です</span>
                            </div>

   {% else %} 

                         {% endif %} <!--空ボトル入荷待ち -->                            
* 2024-11-22 Friday
CRの改行コードの表現にはもう一つの方法があり、下記のように特殊な入力方法で記述できるのです。

[Ctrl + V]、[Ctrl + M]と二文字、入力
* 2024-11-25 Monday

  * wezterm key binds
    ** PANE
      CTRL+SHIFT+ALT	"	SplitVertical={domain="CurrentPaneDomain"}
      CTRL+SHIFT+ALT	%	SplitHorizontal={domain="CurrentPaneDomain"}
      CTRL+SHIFT+ALT	LeftArrow	AdjustPaneSize={"Left", 1}
      same as any direction..
      CTRL+SHIFT	Z	TogglePaneZoomState

